name: CI - Run Tests

on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Executar os testes
      - name: Run tests
        run: npx vitest --run

  create-pull-request:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main
          title: "Auto-merge from dev"
          body: |
            This PR was automatically created from dev after passing the tests.
